### ISSUE TITLE
Bug des pseudos

### ISSUE THREAD

**Issue by AntoineFr** [ReedShalazi/mastermind#1]
Bonjour monsieur,

J'ai installé votre application et j'ai créé la base de données comme il faut, mais j'ai repéré un bug sur le pseudo.
En effet, quand j'utilise mon pseudo favori, certains caractères ne s'affichent pas bien sur le haut de la page, ce qui fait que la mise en page est assez étrange.

Merci d'avance pour votre aide !

Pour reproduire le bug, mon pseudo est `<h1>Antoine</h1>`.

**Comment by ReedShalazi** [comment]
Intéressant.
Que suggérez-vous ?

**Comment by AntoineFr** [comment]
Bonjour monsieur,

Je vous suggère de corriger le problème.

Cordialement,
<h1>Antoine</h1>

**Comment by AntoineFr** [comment]
Merci pour votre aide !
